{% set python_min = '3.10' %}
{% set name = "myjive" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/myjive-{{ version }}.tar.gz
  sha256: 8f5545c3960521024d0c844480452e14a74ec1eba0be2113e1edbbbcf92d31f4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }},<3.11
    - matplotlib-base ==3.5.2
    - numba ==0.56.4
    - numpy ==1.23.5
    - scikit-sparse ==0.4.12
    - scipy ==1.8.1

test:
  imports:
    - myjive
    - myjivex
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.tudelft.nl/apoot1/myjive
  summary: Personal implementation of jive C++ library in Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - annepoot
